# Dependencies
plugins:          [jekyll-paginate, jekyll-redirect-from]

# Features
excerpt_separator: <!--more-->
categories:       "investing|finance|customer_analytics|data|musings|life"

# Permalinks
permalink:        /:year/:month/:day/:title/

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Steven Ripplinger
tagline:          'writings & other projects'
description:      'writings & other projects'
url:              'https://steveripplinger.com'
baseurl:          ''
imageurl:         'https://steveripplinger.com/assets/images/'

author:
  name:           'Steven Ripplinger'
  url:            https://www.linkedin.com/in/steve-ripplinger/

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/sripplin


social:
    linkedin:     https://www.linkedin.com/in/steve-ripplinger/
    twitter:      https://twitter.com/steveripplinger

# Structure
paginate:         15
incl_image_featured:  false